-- MySQL Script generated by MySQL Workbench
-- Thu Apr 19 07:30:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Transito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Transito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Transito` DEFAULT CHARACTER SET utf8 ;
USE `Transito` ;

-- -----------------------------------------------------
-- Table `Transito`.`Conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Conductor` (
  `idConductor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apPaterno` VARCHAR(45) NOT NULL,
  `apMaterno` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NOT NULL,
  `noLicencia` VARCHAR(12) NOT NULL,
  `telCelular` INT(10) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idConductor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Aseguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Aseguradora` (
  `idAseguradora` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAseguradora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Color` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Vehiculo` (
  `noPlaca` VARCHAR(10) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `anio` INT(4) NOT NULL,
  `noPolizaSeguro` VARCHAR(45) NULL,
  `idMarca` INT NOT NULL,
  `idAseguradora` INT NULL,
  `idColor` INT NOT NULL,
  `idConductor` INT NULL,
  PRIMARY KEY (`noPlaca`),
  INDEX `fk_Vehiculo_Conductor1_idx` (`idConductor` ASC),
  INDEX `fk_Vehiculo_Marca1_idx` (`idMarca` ASC),
  INDEX `fk_Vehiculo_Aseguradora1_idx` (`idAseguradora` ASC),
  INDEX `fk_Vehiculo_Color1_idx` (`idColor` ASC),
  CONSTRAINT `fk_Vehiculo_Conductor1`
    FOREIGN KEY (`idConductor`)
    REFERENCES `Transito`.`Conductor` (`idConductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Marca1`
    FOREIGN KEY (`idMarca`)
    REFERENCES `Transito`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Aseguradora1`
    FOREIGN KEY (`idAseguradora`)
    REFERENCES `Transito`.`Aseguradora` (`idAseguradora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Color1`
    FOREIGN KEY (`idColor`)
    REFERENCES `Transito`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Reporte` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `latitud` FLOAT NOT NULL,
  `longitud` FLOAT NOT NULL,
  `nombreSiniestro` VARCHAR(45) NOT NULL,
  `apPaternoSiniestro` VARCHAR(45) NOT NULL,
  `apMaternoSiniestro` VARCHAR(45) NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `idConductor` INT NOT NULL,
  `idVehiculoConductor` VARCHAR(10) NOT NULL,
  `idVehiculoSiniestro` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reporte_Conductor1_idx` (`idConductor` ASC),
  INDEX `fk_Reporte_Vehiculo1_idx` (`idVehiculoConductor` ASC),
  INDEX `fk_Reporte_Vehiculo2_idx` (`idVehiculoSiniestro` ASC),
  CONSTRAINT `fk_Reporte_Conductor1`
    FOREIGN KEY (`idConductor`)
    REFERENCES `Transito`.`Conductor` (`idConductor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Vehiculo1`
    FOREIGN KEY (`idVehiculoConductor`)
    REFERENCES `Transito`.`Vehiculo` (`noPlaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Vehiculo2`
    FOREIGN KEY (`idVehiculoSiniestro`)
    REFERENCES `Transito`.`Vehiculo` (`noPlaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apPaterno` VARCHAR(45) NOT NULL,
  `apMaterno` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idCargo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Perito_Cargo1_idx` (`idCargo` ASC),
  CONSTRAINT `fk_Perito_Cargo1`
    FOREIGN KEY (`idCargo`)
    REFERENCES `Transito`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`DictamenReporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`DictamenReporte` (
  `folio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `idReporte` INT NOT NULL,
  `idPerito` INT NOT NULL,
  PRIMARY KEY (`folio`),
  INDEX `fk_DictamenReporte_Reporte_idx` (`idReporte` ASC),
  INDEX `fk_DictamenReporte_Perito1_idx` (`idPerito` ASC),
  CONSTRAINT `fk_DictamenReporte_Reporte`
    FOREIGN KEY (`idReporte`)
    REFERENCES `Transito`.`Reporte` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DictamenReporte_Perito1`
    FOREIGN KEY (`idPerito`)
    REFERENCES `Transito`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transito`.`Fotografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transito`.`Fotografia` (
  `idFotografia` INT NOT NULL AUTO_INCREMENT,
  `foto` BLOB NOT NULL,
  `idReporte` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  PRIMARY KEY (`idFotografia`),
  INDEX `fk_Fotografia_Reporte1_idx` (`idReporte` ASC),
  CONSTRAINT `fk_Fotografia_Reporte1`
    FOREIGN KEY (`idReporte`)
    REFERENCES `Transito`.`Reporte` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
